In [14]:
import numpy as np
#create a ARRAY that holds a scalar
s=np.array(5)
print(s)
s.shape
v=s+9
print(v)
v=np.array([1,2,3])
v.shape
x=v[1:]
print(x)
m = np.array([[1,2,3], [4,5,6], [7,8,9]])
m[1][2]

5
14
[2 3]


6

In [16]:
import numpy as np
values = [1,2,3,4,5]
values = np.array(values) + 5
print(values)

[ 6  7  8  9 10]


In [19]:
import numpy as np

values+=5
print(values)

[21 22 23 24 25]


In [25]:
import numpy as np
h=[1,2,3,4]
#x=np.multiply(h,8)
#print(x)
x=np.array(h)*8
print(x)
m.T
x.shape



[ 8 16 24 32]


(4,)